export const heroStats = [
  { n: '150+', l: 'Cultivadores' },
  { n: '24/7', l: 'Monitoreo' },
  { n: '100%', l: 'Trazabilidad' },
];

export const panelConfig = [
  {
    tag: 'Gestión de Cultivo',
    tagCls: 'bg-lime-400/10 border-lime-400/20 text-lime-300',
    title: 'Control ',
    hl: 'total',
    end: ' de cada planta',
    desc: 'Registrá pH, EC, nutrientes y fases de crecimiento. Nuestra IA te sugiere correcciones en tiempo real para maximizar tu cosecha.',
    chips: ['pH/EC', 'IA', 'Fases', 'Lab Reports'],
    chipCls: 'bg-lime-400/10 text-lime-300 border-lime-400/20',
    glow: 'rgba(163,230,53,0.2)',
    orbColor: 'rgba(163,230,53,0.12)',
    orbColor2: 'rgba(34,197,94,0.08)',
    bgImage: '/images/bg/cultivo.jpg',
  },
  {
    tag: 'Market',
    tagCls: 'bg-emerald-400/10 border-emerald-400/20 text-emerald-300',
    title: 'Tu ',
    hl: 'mercado',
    end: ' cannábico',
    desc: 'Comprá y vendé genéticas, nutrientes y equipos. Reseñas verificadas, informes de laboratorio y reputación de vendedores.',
    chips: ['Genéticas', 'Nutrientes', 'Equipos', 'Reseñas'],
    chipCls: 'bg-emerald-400/10 text-emerald-300 border-emerald-400/20',
    glow: 'rgba(16,185,129,0.2)',
    orbColor: 'rgba(6,182,212,0.1)',
    orbColor2: 'rgba(16,185,129,0.08)',
    bgImage: '/images/bg/market.jpg',
  },
  {
    tag: 'Comunidad',
    tagCls: 'bg-amber-400/10 border-amber-400/20 text-amber-300',
    title: 'Compartí y ',
    hl: 'aprendé',
    end: '',
    desc: 'Debates, papers, investigaciones y eventos. Una comunidad de cultivadores que comparte conocimiento y experiencia real.',
    chips: ['Debates', 'Papers', 'Eventos', 'Tips'],
    chipCls: 'bg-amber-400/10 text-amber-300 border-amber-400/20',
    glow: 'rgba(251,191,36,0.15)',
    orbColor: 'rgba(251,191,36,0.08)',
    orbColor2: 'rgba(245,158,11,0.05)',
    bgImage: '/images/bg/community.jpg',
  },
];

export const features = [
  {
    icon: '🌱',
    title: 'Tracking de Cultivos',
    desc: 'Registrá cada bucket con log semanal de pH, EC, nutrientes y fases.',
    gradient: 'from-lime-300 to-green-600',
    glow: 'rgba(163,230,53,0.3)',
    border: 'border-lime-400/15 hover:border-lime-400/40',
    bg: 'bg-lime-400/10 group-hover:bg-lime-400/25',
  },
  {
    icon: '🧪',
    title: 'Lab Reports',
    desc: 'Informes de laboratorio verificados. Trazabilidad del esqueje a la cosecha.',
    gradient: 'from-emerald-300 to-teal-600',
    glow: 'rgba(16,185,129,0.3)',
    border: 'border-emerald-400/15 hover:border-emerald-400/40',
    bg: 'bg-emerald-400/10 group-hover:bg-emerald-400/25',
  },
  {
    icon: '🤖',
    title: 'IA Integrada',
    desc: 'Sugerencias de pH/EC y nutrientes basadas en la fase de tu cultivo.',
    gradient: 'from-cyan-300 to-blue-600',
    glow: 'rgba(6,182,212,0.3)',
    border: 'border-cyan-400/15 hover:border-cyan-400/40',
    bg: 'bg-cyan-400/10 group-hover:bg-cyan-400/25',
  },
  {
    icon: '🛒',
    title: 'Market',
    desc: 'Comprá y vendé genéticas, nutrientes y equipos con reseñas reales.',
    gradient: 'from-amber-300 to-orange-600',
    glow: 'rgba(251,191,36,0.3)',
    border: 'border-amber-400/15 hover:border-amber-400/40',
    bg: 'bg-amber-400/10 group-hover:bg-amber-400/25',
  },
  {
    icon: '📊',
    title: 'Panel de Admin',
    desc: 'Dashboard con KPIs, gestión de usuarios, tokens y transacciones.',
    gradient: 'from-violet-300 to-purple-600',
    glow: 'rgba(139,92,246,0.3)',
    border: 'border-violet-400/15 hover:border-violet-400/40',
    bg: 'bg-violet-400/10 group-hover:bg-violet-400/25',
  },
  {
    icon: '🎪',
    title: 'Eventos',
    desc: 'Organizá y descubrí eventos, clases y meetups con reservas integradas.',
    gradient: 'from-rose-300 to-pink-600',
    glow: 'rgba(244,63,94,0.3)',
    border: 'border-rose-400/15 hover:border-rose-400/40',
    bg: 'bg-rose-400/10 group-hover:bg-rose-400/25',
  },
];

export const marketItems = [
  { name: 'Blue Dream Seeds', price: '$25', r: 4.8, e: '🌱', s: '142' },
  { name: 'Flora Trio Pack', price: '$38', r: 4.6, e: '🧪', s: '89' },
  { name: 'LED Grow 600W', price: '$185', r: 4.9, e: '💡', s: '64' },
  { name: 'Coco Coir 50L', price: '$12', r: 4.5, e: '🥥', s: '210' },
  { name: 'pH Meter Pro', price: '$45', r: 4.7, e: '📊', s: '156' },
  { name: 'Air Pump Kit', price: '$28', r: 4.4, e: '💨', s: '93' },
];

export const communityPosts = [
  {
    a: 'María G.',
    av: '🧑‍🌾',
    t: '2h',
    title: 'Mi primera cosecha!',
    c: 'Después de 12 semanas, finalmente corté mi Blue Dream...',
    l: 24,
    cm: 8,
    tag: 'Showcase',
    tc: 'text-emerald-400 bg-emerald-400/10',
  },
  {
    a: 'Carlos R.',
    av: '👨‍🔬',
    t: '5h',
    title: 'Tips pH estable en floración',
    c: 'Un método con resultados increíbles. La clave está en la frecuencia...',
    l: 15,
    cm: 12,
    tag: 'Tips',
    tc: 'text-amber-400 bg-amber-400/10',
  },
  {
    a: 'Laura M.',
    av: '👩‍🔬',
    t: '1d',
    title: 'Espectro LED y terpenos',
    c: 'Resultados de mi investigación sobre espectros de luz...',
    l: 42,
    cm: 19,
    tag: 'Research',
    tc: 'text-cyan-400 bg-cyan-400/10',
  },
];

export const ecosystemWords = [
  'Hidroponía',
  'Orgánico',
  'Sales Minerales',
  'Mixto',
  'Lab Reports',
  'Trazabilidad',
  'Genéticas',
  'Comunidad',
];
