import { ForumPost } from '@/types/forum';

export const INITIAL_FORUM_DATA: ForumPost[] = [
  // CATEGORÍA: Investigación
  {
    id: '1',
    author: {
      name: 'Dr. Hydro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hydro',
      role: 'Expert',
    },
    category: 'Investigación',
    title: 'Optimización de PH en sistemas NFT mediante sensores inteligentes',
    content: 'En esta investigación exploramos cómo la integración de sensores de bajo costo puede mejorar la precisión del PH en sistemas NFT, reduciendo el desperdicio de nutrientes en un 15%.',
    images: ['https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=1000'],
    stats: { likes: 42, views: 1250 },
    comments: [],
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'inv-2',
    author: { name: 'Bio_Gen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bio', role: 'Expert' },
    category: 'Investigación',
    title: 'Resistencia a plagas: Análisis de terpenos en cepas locales',
    content: 'Estudio comparativo sobre cómo ciertos perfiles de terpenos actúan como repelentes naturales contra la arañuela roja.',
    images: ['/images/market/8.jpg'],
    stats: { likes: 38, views: 920 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'inv-3',
    author: { name: 'SoilMaster', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Soil', role: 'User' },
    category: 'Investigación',
    title: 'Microrrizas y su impacto en la absorción de Fósforo',
    content: 'Resultados tras 6 meses de pruebas controladas usando diferentes inóculos comerciales en sustratos orgánicos.',
    images: ['/images/market/1.jpg', '/images/market/2.jpg', '/images/market/3.jpg'],
    stats: { likes: 55, views: 2100 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },

  // CATEGORÍA: Papers
  {
    id: 'paper-1',
    author: { name: 'CannaScience', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Science', role: 'Staff' },
    category: 'Papers',
    title: 'Libro Blanco: El futuro de la automatización en cultivos indoor',
    content: 'Descargá el último paper sobre integración de IA y Machine Learning en salas de cultivo a gran escala.',
    images: ['/images/market/20.jpg'],
    stats: { likes: 89, views: 4500 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'paper-2',
    author: { name: 'Dr. Bloom', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bloom', role: 'Expert' },
    category: 'Papers',
    title: 'Protocolos de secado y curado: Ciencia detrás del aroma',
    content: 'Análisis químico de la degradación de cannabinoides según diferentes curvas de temperatura y humedad.',
    images: ['/images/market/15.jpg'],
    stats: { likes: 120, views: 6700 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'paper-3',
    author: { name: 'Legal_Grow', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Legal', role: 'Staff' },
    category: 'Papers',
    title: 'Marco Regulatorio 2026: Guía completa para clubes',
    content: 'Documento detallado sobre las nuevas normativas de trazabilidad y dispensación en el territorio nacional.',
    images: ['/images/market/3.jpg', '/images/market/4.jpg'],
    stats: { likes: 230, views: 12000 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },

  // CATEGORÍA: Debate
  {
    id: '3',
    author: {
      name: 'User_442',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=User',
      role: 'User',
    },
    category: 'Debate',
    title: '¿LED vs HPS para floración en climas tropicales?',
    content: 'Abro debate sobre qué tipo de iluminación rinde mejor en ambientes con alta humedad y temperaturas constantes sobre los 28 grados.',
    stats: { likes: 28, views: 890 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'deb-2',
    author: { name: 'Organic_Only', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Organic', role: 'User' },
    category: 'Debate',
    title: 'Sales vs Orgánico: ¿Realmente hay diferencia en el sabor?',
    content: 'Mucho se dice del lavado de raíces, pero ¿qué dicen las catas a ciegas? Los leo.',
    stats: { likes: 156, views: 3400 },
    comments: [],
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'deb-3',
    author: { name: 'Indoor_Pro', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pro', role: 'User' },
    category: 'Debate',
    title: 'Defoliación extrema: ¿Mito o incremento real de cosecha?',
    content: 'Vengo probando Schwazzing hace dos ciclos y no estoy convencido. ¿Alguna experiencia real?',
    stats: { likes: 67, views: 1500 },
    comments: [],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },

  // CATEGORÍA: Anuncio
  {
    id: '2',
    author: {
      name: 'Mariana_Tech',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana',
      role: 'Staff',
    },
    category: 'Anuncio',
    title: 'Nuevos protocolos de seguridad para el Citroforo',
    content: 'Estamos implementando nuevas medidas para asegurar que la información compartida en los Papers sea verificada por nuestra red de expertos.',
    stats: { likes: 15, views: 540 },
    comments: [],
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'ann-2',
    author: { name: 'Citronela_Official', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Official', role: 'Staff' },
    category: 'Anuncio',
    title: '¡Lanzamiento de la nueva línea de nutrientes Citromarket!',
    content: 'Ya están disponibles los packs premium para floración. Consultá stock en el marketplace.',
    image: '/images/market/10.jpg',
    stats: { likes: 450, views: 25000 },
    comments: [],
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'ann-3',
    author: { name: 'Admin', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin', role: 'Staff' },
    category: 'Anuncio',
    title: 'Mantenimiento programado de la plataforma',
    content: 'Este domingo de 02:00 a 04:00 AM estaremos realizando mejoras en el sistema de mensajería.',
    stats: { likes: 5, views: 200 },
    comments: [],
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  }
];
